language: python
python:
  - "3.6"
# command to install dependencies
# make sure the empty distance is two spaces not tab key 
install:
  - "pip install -r requirements.txt"
# command to run tests
script: py.test
